name: okami

services:
  workers:
    build: .
    container_name: workers
    restart: always
    ports:
      - 5000:5000
    environment:
      - REDIS_HOST=${REDIS_HOST}
      - REDIS_PORT=${REDIS_PORT}
      - REDIS_PASSWORD=${REDIS_PASSWORD}
      - OKAMI_BASE_URL=${OKAMI_BASE_URL}
      - API_PORT=${API_PORT}




