version: '3.7'


services:
  workers:
    networks:
      - default
    build: .
    container_name: okami-workers
    restart: always
    ports:
      - 5000:5000
    environment:
      - REDIS_HOST=${REDIS_HOST}
      - REDIS_PORT=${REDIS_PORT}
      - REDIS_PASSWORD=${REDIS_PASSWORD}
      - OKAMI_BASE_URL=${OKAMI_BASE_URL}
      - API_PORT=${API_PORT}




networks:
  default:
    external:
      name: okami-default-network



